## 作業三

### 方法一

In [1]:
! wget https://raw.githubusercontent.com/ywchiu/tibame_tm/master/data/creditcard_titles.csv

--2020-07-29 11:32:37--  https://raw.githubusercontent.com/ywchiu/tibame_tm/master/data/creditcard_titles.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3688 (3.6K) [text/plain]
Saving to: ‘creditcard_titles.csv’

creditcard_titles.c 100%[===================>]   3.60K  --.-KB/s    in 0s      

2020-07-29 11:32:37 (60.6 MB/s) - ‘creditcard_titles.csv’ saved [3688/3688]



In [9]:
titles = []
with open('creditcard_titles.csv') as f:
  for line in f.readlines()[1:]:
    titles.append(line.strip().split(',')[1])

In [23]:
#titles

### 方法二

In [13]:
import pandas
df = pandas.read_csv('creditcard_titles.csv', index_col = 0)

In [17]:
titles = df['title'].tolist()

### 方法三

In [18]:
import pandas
df = pandas.read_csv('https://raw.githubusercontent.com/ywchiu/tibame_tm/master/data/creditcard_titles.csv', index_col = 0)

In [22]:
titles = df['title'].tolist()

In [31]:
import jieba
jieba.add_word('台新')
jieba.add_word('富邦')
jieba.load_userdict('userdict.txt')
corpus = []
for title in titles:
  corpus.append(' '.join(jieba.cut(title)))
#print(corpus)

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(stop_words = ['不是'])
X = vectorizer.fit_transform(corpus)

In [37]:
print(vectorizer.get_feature_names())

['10', '109', '15', '150', '18', '2020', '50', 'ana', 'app', 'apple', 'bear', 'costco', 'gogo', 'happy', 'hello', 'icash', 'kitty', 'line', 'linepay', 'money', 'money101', 'only', 'pay', 'pi', 're', 'ubear', 'ubereat', 'wallet', 'youbike2', '三代', '三倍', '三越', '上市', '上網', '上路', '下半年', '不划算', '世界', '中信', '中油', '付款', '位券', '使用', '促刷', '信用卡', '倍券', '優惠', '元大', '兆豐', '全新', '凱基', '分期', '分眾', '列入', '刷卡', '券綁', '加碼', '助理', '匯豐', '匯豐及', '卡娜', '卡換', '卡新戶禮', '卡會', '卡未核', '卡申', '卡莉', '卡面', '可以', '台哥', '台新', '合庫', '名額', '售票', '商務御璽', '商機', '問去', '問題', '嘟嘟', '回饋', '國旅', '國泰', '園學費', '土地', '城市', '外幣', '多家', '大滿', '大聯名', '太陽', '如何', '學貸', '家人', '寄來', '富邦', '寰宇', '小白', '屈臣氏', '年繳', '幼兒', '張高', '影城', '御璽', '心得', '悍將', '悠遊', '情報', '感謝', '應援哩', '懶人包', '房停車', '折抵', '抽獎', '拚振興', '指定', '振新券', '振興券', '掛號', '推數', '推薦', '推銷', '改換', '整理', '新光', '新戶', '新聞', '星展', '最新', '有人', '未過', '本月', '查詢', '核卡', '樂天', '樂跑', '正常', '永豐幣', '沒有', '活動', '消費', '渣打', '炫晶', '無限卡享', '熊回饋', '燃料', '玉山', '現金', '申請', '疑問', '研究', '神奇', '算實體'

In [33]:
X

<71x198 sparse matrix of type '<class 'numpy.int64'>'
	with 451 stored elements in Compressed Sparse Row format>

In [38]:
import re
corpus = []
for title in titles:
  segwords = []
  for word in jieba.cut(title):
    m = re.match('[\u4e00-\u9fa5]+', word)
    if m:
      segwords.append(word)
  corpus.append(' '.join(segwords))

In [39]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

In [40]:
print(vectorizer.get_feature_names())

['三代', '三倍', '三越', '上市', '上網', '上路', '下半年', '不划算', '不是', '世界', '中信', '中油', '付款', '位券', '使用', '促刷', '信用卡', '倍券', '優惠', '元大', '兆豐', '全新', '凱基', '分期', '分眾', '列入', '刷卡', '券綁', '加碼', '助理', '匯豐', '匯豐及', '卡娜', '卡換', '卡新戶禮', '卡會', '卡未核', '卡申', '卡莉', '卡面', '可以', '台哥', '台新', '合庫', '名額', '售票', '商務御璽', '商機', '問去', '問題', '嘟嘟', '回饋', '國旅', '國泰', '園學費', '土地', '城市', '外幣', '多家', '大滿', '大聯名', '太陽', '如何', '學貸', '家人', '寄來', '富邦', '寰宇', '小白', '屈臣氏', '年繳', '幼兒', '張高', '影城', '御璽', '心得', '悍將', '悠遊', '情報', '感謝', '應援哩', '懶人包', '房停車', '折抵', '抽獎', '拚振興', '指定', '振新券', '振興券', '掛號', '推數', '推薦', '推銷', '改換', '整理', '新光', '新戶', '新聞', '星展', '最新', '有人', '未過', '本月', '查詢', '核卡', '樂天', '樂跑', '正常', '永豐幣', '沒有', '活動', '消費', '渣打', '炫晶', '無限卡享', '熊回饋', '燃料', '玉山', '現金', '申請', '疑問', '研究', '神奇', '算實體', '簡訊', '粉紅', '紙本', '紙本券', '經濟部', '線上', '繳卡費', '繳稅', '繳納', '繳費', '聯名', '聯邦', '聯邦卡', '自動', '花旗', '討論', '調額', '請問', '謄本', '證明', '財力', '貫之路', '費用', '賴點', '近視', '這是', '通路', '金卡', '金融', '金袋', '金額', '銀行', '鑽金', '閒聊', '關於', '限制', '雷射', '電話',

In [41]:
import re
corpus = []
for title in titles:
  corpus.append([word for word in jieba.cut(title) if re.match('[\u4e00-\u9fa5]+', word)])
  

In [42]:
class ChineseCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(ChineseCountVectorizer, self).build_analyzer()
        return lambda doc: (w for w in analyzer(doc) if re.match('[\u4e00-\u9fa5]+', w))

In [43]:
corpus = []
for title in titles:
  corpus.append(' '.join(jieba.cut(title)))

In [44]:
vectorizer = ChineseCountVectorizer()
X = vectorizer.fit_transform(corpus)

In [45]:
print(vectorizer.get_feature_names())

['三代', '三倍', '三越', '上市', '上網', '上路', '下半年', '不划算', '不是', '世界', '中信', '中油', '付款', '位券', '使用', '促刷', '信用卡', '倍券', '優惠', '元大', '兆豐', '全新', '凱基', '分期', '分眾', '列入', '刷卡', '券綁', '加碼', '助理', '匯豐', '匯豐及', '卡娜', '卡換', '卡新戶禮', '卡會', '卡未核', '卡申', '卡莉', '卡面', '可以', '台哥', '台新', '合庫', '名額', '售票', '商務御璽', '商機', '問去', '問題', '嘟嘟', '回饋', '國旅', '國泰', '園學費', '土地', '城市', '外幣', '多家', '大滿', '大聯名', '太陽', '如何', '學貸', '家人', '寄來', '富邦', '寰宇', '小白', '屈臣氏', '年繳', '幼兒', '張高', '影城', '御璽', '心得', '悍將', '悠遊', '情報', '感謝', '應援哩', '懶人包', '房停車', '折抵', '抽獎', '拚振興', '指定', '振新券', '振興券', '掛號', '推數', '推薦', '推銷', '改換', '整理', '新光', '新戶', '新聞', '星展', '最新', '有人', '未過', '本月', '查詢', '核卡', '樂天', '樂跑', '正常', '永豐幣', '沒有', '活動', '消費', '渣打', '炫晶', '無限卡享', '熊回饋', '燃料', '玉山', '現金', '申請', '疑問', '研究', '神奇', '算實體', '簡訊', '粉紅', '紙本', '紙本券', '經濟部', '線上', '繳卡費', '繳稅', '繳納', '繳費', '聯名', '聯邦', '聯邦卡', '自動', '花旗', '討論', '調額', '請問', '謄本', '證明', '財力', '貫之路', '費用', '賴點', '近視', '這是', '通路', '金卡', '金融', '金袋', '金額', '銀行', '鑽金', '閒聊', '關於', '限制', '雷射', '電話',

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

## Euclidean Distance

In [47]:
contents = ['This is a toy post about machine learning. Actually, it contains not much interesting stuff.',
'Imaging databases can get huge.',
'Most imaging databases safe images permanently.',
'Imaging databases store images.',
'Imaging databases store images. Imaging databases store images. Imaging databases store images.']

In [50]:
corpus = []
for doc in contents:
  corpus.append(doc.lower())

In [51]:
corpus = [doc.lower() for doc in contents]

In [52]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

In [53]:
X

<5x24 sparse matrix of type '<class 'numpy.int64'>'
	with 33 stored elements in Compressed Sparse Row format>

In [56]:
X[0].toarray().flatten()

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1])

In [57]:
X[1].toarray().flatten()

array([0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [61]:
import math
math.sqrt(sum((X[0].toarray().flatten() - X[1].toarray().flatten()) ** 2))

4.358898943540674

In [63]:
import scipy as sp

def dist_raw(v1, v2):
  delta = v1-v2
  return sp.linalg.norm(delta.toarray())


In [66]:
dist_raw(X[0] ,X[1] )

4.358898943540674

In [67]:
from sklearn.metrics.pairwise import euclidean_distances
euclidean_distances(X)

array([[0.        , 4.35889894, 4.47213595, 4.24264069, 7.07106781],
       [4.35889894, 0.        , 2.64575131, 2.23606798, 5.38516481],
       [4.47213595, 2.64575131, 0.        , 2.        , 4.89897949],
       [4.24264069, 2.23606798, 2.        , 0.        , 4.        ],
       [7.07106781, 5.38516481, 4.89897949, 4.        , 0.        ]])

## Jaccard Similarity

In [70]:
import numpy as np
a = np.array([3,3,1,0,0,2])
(a > 0).astype(int)

array([1, 1, 1, 0, 0, 1])

In [71]:
np.asarray(a, np.bool)

array([ True,  True,  True, False, False,  True])

In [75]:
def jaccard(v1,v2):
  v1 = np.asarray(v1, np.bool)
  v2 = np.asarray(v2, np.bool)
  return np.double(np.bitwise_and(v1, v2).sum()) / np.double(np.bitwise_or(v1, v2).sum())

In [77]:
jaccard(X[0].toarray().flatten(),X[1].toarray().flatten())

0.0

In [78]:
jaccard(X[3].toarray().flatten(),X[4].toarray().flatten())

1.0

In [80]:
from sklearn.metrics import jaccard_score
v1 = np.asarray(X[3].toarray().flatten(), np.bool)
v2 = np.asarray(X[4].toarray().flatten(), np.bool)
jaccard_score(v1, v2)

1.0

In [82]:
X.shape

(5, 24)

In [83]:
X.shape[0]

5

In [84]:
n = X.shape[0]

In [86]:
m = np.zeros((n,n))
m

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [87]:
for i in range(n):
  for j in range(n):
    v1 = np.asarray(X[i].toarray().flatten(), np.bool)
    v2 = np.asarray(X[j].toarray().flatten(), np.bool)
    m[i,j] = jaccard_score(v1, v2)

In [88]:
m

array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.22222222, 0.28571429, 0.28571429],
       [0.        , 0.22222222, 1.        , 0.42857143, 0.42857143],
       [0.        , 0.28571429, 0.42857143, 1.        , 1.        ],
       [0.        , 0.28571429, 0.42857143, 1.        , 1.        ]])

## Cosine Slimilarity

In [91]:
import math
def cos_similarity(v1,v2):
  return np.dot(v1,v2) / math.sqrt((v1 ** 2).sum()) * math.sqrt((v2 ** 2).sum())

In [92]:
cos_similarity(X[0].toarray().flatten(),X[1].toarray().flatten())

0.0

In [94]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(X)

array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.36514837, 0.4472136 , 0.4472136 ],
       [0.        , 0.36514837, 1.        , 0.61237244, 0.61237244],
       [0.        , 0.4472136 , 0.61237244, 1.        , 1.        ],
       [0.        , 0.4472136 , 0.61237244, 1.        , 1.        ]])

In [95]:
from sklearn.metrics.pairwise import cosine_distances
cosine_distances(X)

array([[0.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 0.        , 0.63485163, 0.5527864 , 0.5527864 ],
       [1.        , 0.63485163, 0.        , 0.38762756, 0.38762756],
       [1.        , 0.5527864 , 0.38762756, 0.        , 0.        ],
       [1.        , 0.5527864 , 0.38762756, 0.        , 0.        ]])

In [ ]:
# distance = 1 - similarity
# similarity = 1 - distance

## TF-IDF

In [96]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)


In [97]:
X

<5x24 sparse matrix of type '<class 'numpy.float64'>'
	with 33 stored elements in Compressed Sparse Row format>

In [98]:
X.toarray()

array([[0.26726124, 0.26726124, 0.        , 0.26726124, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.26726124,
        0.26726124, 0.26726124, 0.26726124, 0.26726124, 0.        ,
        0.26726124, 0.26726124, 0.        , 0.26726124, 0.        ,
        0.        , 0.26726124, 0.26726124, 0.26726124],
       [0.        , 0.        , 0.52451722, 0.        , 0.29550385,
        0.52451722, 0.52451722, 0.        , 0.29550385, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.27880274,
        0.        , 0.        , 0.33142212, 0.27880274, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.49487286,
        0.        , 0.        , 0.49487286, 0.        , 0.49487286,
        0.        , 0.        , 0.        , 0.        ],
       [0.   

In [99]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(X)

array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.16477457, 0.25283852, 0.25283852],
       [0.        , 0.16477457, 1.        , 0.40709381, 0.40709381],
       [0.        , 0.25283852, 0.40709381, 1.        , 1.        ],
       [0.        , 0.25283852, 0.40709381, 1.        , 1.        ]])